# Site settings
name: 火柴棍
email: pengyao_fo@163.com
author: 火柴棍
url:
resume_site:
github: https://github.com/fingerkiller/
baseurl: ""
description: Actually, less is more!
meta_description: 读万卷书，行万里路
motto: It's our wits that make us men.
banner: 读万卷书，行万里路

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: fingerkiller
highlighter: rouge

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
